{
 "title": "Nginx Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"nginx-app\"},namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"},cluster)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Scrape y Conexiones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Estado Último Scrape",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Histórico Conexiones Activas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 1 },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Histórico Conexiones Procesadas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "irate(nginx_connections_handled[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Histórico de peticiones HTTP totales",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Uso de Recursos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Uso de CPU (del límite)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "description": "Se actualiza con los selectores globales de Pod y Container. \n\nSi un Pod o Container tiene establecido un atributo para request o limit se mostrará en la gráfica.",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "scalar(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=\"$pod\", container=~\"$container\", container!=\"\", container!=\"POD\", resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=\"$pod\", container=~\"$container\", container!=\"\", container!=\"POD\", resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Uso de Memoria (del límite)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Uso de Memoria (sin caché)",
   "type": "timeseries",
   "description": "Se actualiza con los selectores globales de Pod y Container. \n\nSi un Pod o Container tiene establecido un atributo para request o limit se mostrará en la gráfica.",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=~\"$namespace\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "scalar(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=\"$pod\", container=~\"$container\", container!=\"\", container!=\"POD\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=\"$pod\", container=~\"$container\", container!=\"\", container!=\"POD\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  { "title": "Alertas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  { "title": "Lista Alertas", "type": "alertlist", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 } }
 ]
}