apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  namespace: nginx-app
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
    - nginx-app
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  endpoints:
  - port: metrics
    path: /metrics
    # interval: 30s
